### ISSUE TITLE
extract SPO datagram error

### ISSUE THREAD

**Issue by AlexZanini70** [valschmidt/kmall#14]
Hi, I have used your script to try to extract the SPO datagram so I have added the following function to extract the SPO datagrams.

![image](https://user-images.githubusercontent.com/97609991/220111510-56741859-2841-4eee-8ba6-0e632d5621d5.png)

this works for the majority of the kmall files logged with our SIS5 system but or few of them we get this error

![image](https://user-images.githubusercontent.com/97609991/220111408-660d9b19-56dc-4fe7-9c19-19aa38dc5671.png)

Unfortunately my python / datagram decoding skills are pretty low so I was wondering if you could have a look.. I might be able to provide you the kmall file..

**Comment by valschmidt** [comment]
I think I see the problem. A data sample would help to confirm it. 

Just so I don't forget, let me try to explain it, if only to myself, for when I get around to sorting it out. 

The SPO datagram is for external navigation sensors. The packet contains both the data after having correcting it for the sensor offsets, and the raw data as sent by the sensor. The raw data as sent by the sensor is packed into a byte array whose length is a maximum of 250 bytes. This is set in a #define statement of the c-header - 
`#define MAX_SPO_DATALENGTH   250`

The code as written probably works as long as the full 250 bytes is used for the raw sensor data, as a full 250 bytes are read each time. But if for some reason fewer bytes are used the read will likely fail, or will not be interpreted correctly. Seems like if this happened in the middle of a file, it would not cause an error that the buffer is of sufficient size. Maybe it happens but is hidden as long as the indexing works properly. Seems like this particular error happens when the file pointer is at the end of the file and there aren't sufficient bytes left for the read. Maybe this is the case in which recording has stopped without a full 250 bytes to be written. 

The parent packet is designed like this:

 ```
struct EMdgmSPO_def
 {
         struct EMdgmHeader_def header;
         struct EMdgmScommon_def cmnPart;
         struct EMdgmSPOdataBlock_def sensorData;
 };
```
The thing to check is if the datagram length field that is contained as part of `EMdgmScommon_def` is the size of just the `EMdgmScommon_def` struct itself (which is what was at least initially thought), or if it is the entire `EMdgmSPO_def` datagram. In that case, it could be passed into the function to read the `SPOdataBlock` and this hopefully will read only the bytes available.

**Comment by AlexZanini70** [comment]
thanks for getting back to me so quickly, really appreciate it :)

I have uploaded a test file to my google drive https://drive.google.com/file/d/1knPsmxEsFNR97_h-ly0mRfwI7zQnH7FF/view?usp=share_link

**Comment by valschmidt** [comment]
Fixed.
